#+TITLE: Phidgets SBC Setup
#+AUTHOR: Peter Polidoro
#+EMAIL: peterpolidoro@gmail.com

* Phidgets SBC User Guide

  [[https://www.phidgets.com/docs/SBC3003_User_Guide][PhidgetSBC4 User Guide]]

* Setup Host Computer

  Install latest Phidget drivers on your host machine.

** Windows

   [[https://www.phidgets.com/downloads/phidget22/libraries/windows/Phidget22-x86.exe][32 Bit Installer Download]]

   [[https://www.phidgets.com/downloads/phidget22/libraries/windows/Phidget22-x64.exe][64 Bit Installer Download]]

** MacOS

   [[https://www.phidgets.com/downloads/phidget22/libraries/macos/Phidget22.dmg][macOS Installer Download]]

** Linux

*** Install Phidget Drivers

    #+BEGIN_SRC sh
      sudo apt-get install build-essential
      sudo apt-get install libusb-1.0-0-dev
    #+END_SRC

    #+BEGIN_SRC sh
      mkdir -p ~/Downloads/phidget/
    #+END_SRC

**** Main Library

     Download this file to ~/Downloads/phidget/

     [[https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22.tar.gz][libphidget22]]

     #+BEGIN_SRC sh
       cd ~/Downloads/phidget
       tar -xvzf libphidget22-*.tar.gz
       cd libphidget22-*/
       ./configure
       make
       sudo make install
       sudo cp plat/linux/udev/99-libphidget22.rules /etc/udev/rules.d
       echo /usr/local/lib | sudo tee -a /etc/ld.so.conf && sudo ldconfig
     #+END_SRC

**** Extra

     Download this file to ~/Downloads/phidget/

     [[https://www.phidgets.com/downloads/phidget22/libraries/linux/libphidget22extra.tar.gz][libphidget22extra]]

     #+BEGIN_SRC sh
       cd ~/Downloads/phidget
       tar -xvzf libphidget22extra-*.tar.gz
       cd libphidget22extra-*/
       ./configure
       make
       sudo make install
     #+END_SRC

**** Admin

     Download this file to ~/Downloads/phidget/

     [[https://www.phidgets.com/downloads/phidget22/tools/linux/phidget22admin.tar.gz][phidget22admin]]

     #+BEGIN_SRC sh
       cd ~/Downloads/phidget
       tar -xvzf phidget22admin-*.tar.gz
       cd phidget22admin-*/
       ./configure
       make
       sudo make install
     #+END_SRC

**** Network Server

     Download this file to ~/Downloads/phidget/

     [[https://www.phidgets.com/downloads/phidget22/servers/linux/phidget22networkserver.tar.gz][phidget22networkserver]]

     #+BEGIN_SRC sh
       cd ~/Downloads/phidget
       tar -xvzf phidget22networkserver-*.tar.gz
       cd phidget22networkserver-*/
       ./configure
       make
       sudo make install
       sudo mkdir -p /etc/phidgets
       sudo cp files/etc/phidgets/* /etc/phidgets/
     #+END_SRC

*** Reboot Host

    #+BEGIN_SRC sh
      sudo reboot now
    #+END_SRC

* Setup SBC

** Flash SBC SD Card Image

***  Host Computer

    #+BEGIN_SRC sh
      cd ~/Downloads
      wget https://www.phidgets.com/downloads/phidgetsbc/SBC3003/phidgetsbc4.zip
      unzip phidgetsbc4.zip
    #+END_SRC

    Plug SD card into host computer and run:

    #+BEGIN_SRC sh
      df -h
    #+END_SRC

    After verifying which device is your SD card (e.g. /dev/sdd1), unmount it
    using the following command:

    #+BEGIN_SRC sh
      umount /dev/sdd1
    #+END_SRC

    Next, we can write the image file to the SD card (be very careful using dd!):
    - if= path to your image
    - of = where to write output (note: do not include partition number)

    Wait for a long time for command to finish.

    #+BEGIN_SRC sh
      sudo dd if=~/Downloads/phidgetsbc4_1.1.0.20180619.img of=/dev/sdd bs=4M
    #+END_SRC

    When dd has finished unmount the SD card:

    #+BEGIN_SRC sh
      df -h
      sudo umount /media/<user>/sdd1
    #+END_SRC

    Remove SD card and insert it into the PhidgetSBC.

** Connect Phidget SBC to the Network

   1. Connect your Phidget SBC to your network using the Ethernet cable.
   2. Connect your Phidget SBC to power. A red LED will immediately light up
      underneath the power barrel, indicating your Phidget SBC is receiving
      power. There is also a green LED that will briefly turn on when power is
      supplied, and then remain on after the SBC has fully booted.

** Find Phidget SBC IP Address

*** Linux

    #+BEGIN_SRC sh
      phidget22admin -s
    #+END_SRC

    Example output:

    #+BEGIN_SRC sh
      Phidget22 Web Server listener phidgetsbc Phidget22 WWW Server phidgetsbc Phidget22 WWW Server:8080 192.168.0.56
      Phidget SBC        PhidgetSBC (00:1b:0b:10:33:9f) PhidgetSBC (00:1b:0b:10:33:9f):80 192.168.0.56
      Phidget22 Server   phidgetsbc                     phidgetsbc:5661          192.168.0.56
    #+END_SRC

    Make note of Phidget SBC IP address (example 192.168.0.56).

** Initialize Settings with SBC Web Interface

   Web Interface Username: admin

   1. Open a browser on host computer to Phidget SBC IP address of (example
      192.168.0.56).
   2. Make new password.
   3. Navigate to Network / Settings and enable SSH Server and Save Changes.
   4. Navigate to System / Packages and check Include full Debian Package
      Repository and Save Changes.
   5. Navigate to System / General and set the correct time zone and Save Changes.
   6. Log out.

** Setup with SBC SSH Interface

*** Create New User

**** SSH into Phidget SBC as root

     Open a terminal on the host computer and ssh into the Phidget SBC.

     #+BEGIN_SRC sh
       ssh root@192.168.0.56
     #+END_SRC

**** Expand SD Card File System

     #+BEGIN_SRC sh
       cd /
       ./expandfs.sh
     #+END_SRC

**** Update Packages

     #+BEGIN_SRC sh
       apt-get update
       apt-get dist-upgrade
     #+END_SRC

**** Add New User and Grant Sudo Privileges

     #+BEGIN_SRC sh
       apt-get install -y sudo
       adduser phidget
       usermod -aG sudo phidget
       exit
     #+END_SRC

*** Setup phidget User and Install Additional Packages

**** SSH into Phidget SBC as phidget

     Open a terminal on the host computer and ssh into the Phidget SBC.

     #+BEGIN_SRC sh
       ssh phidget@192.168.0.56
     #+END_SRC

**** Install Additional Packages

     #+BEGIN_SRC sh
       sudo apt-get install -y wget unzip git
     #+END_SRC

**** Enable Bash Completion

     #+BEGIN_SRC sh
       sudo apt-get install -y bash-completion
       echo 'if [ -f /etc/bash_completion ]; then' | sudo tee -a /etc/profile
       echo ' . /etc/bash_completion' | sudo tee -a /etc/profile
       echo 'fi' | sudo tee -a /etc/profile
     #+END_SRC

**** Grant phidget User Permission to Use Phidgets

     #+BEGIN_SRC sh
       echo 'SUBSYSTEM=="vinthub", GROUP="vinthubuser", MODE="0660"' | sudo tee /etc/udev/rules.d/50-vinthub.rules
       sudo groupadd vinthubuser
       sudo adduser "$USER" vinthubuser
       sudo reboot
     #+END_SRC

**** Setup USB Stick Mounting

     #+BEGIN_SRC sh
       sudo apt-get install -y ntfs-3g
       sudo sed -i 's/FILESYSTEMS="vfat ext2 ext3 ext4 hfsplus"/FILESYSTEMS="vfat ext2 ext3 ext4 hfsplus ntfs fuseblk"/' /etc/usbmount/usbmount.conf
       sudo sed -i 's/FS_MOUNTOPTIONS=""/FS_MOUNTOPTIONS="-fstype=ntfs-3g,nls=utf8,umask=007,gid=46 -fstype=fuseblk,nls=utf8,umask=007,gid=46 -fstype=vfat,gid=1000,uid=1000,umask=007"/' /etc/usbmount/usbmount.conf
       sudo reboot
     #+END_SRC

**** Setup Python

     #+BEGIN_SRC sh
       sudo apt-get install -y python3 python3-venv
       mkdir ~/venvs
       python3 -m venv ~/venvs/phidget
       echo 'source ~/venvs/phidget/bin/activate' >> ~/.bashrc
       source ~/.bashrc
       pip install pip --upgrade
       mkdir ~/Downloads
       cd ~/Downloads
       wget https://www.phidgets.com/downloads/phidget22/libraries/any/Phidget22Python.zip
       unzip Phidget22Python.zip
       cd Phidget22Python/
       pip install .
     #+END_SRC

**** Test Python

     #+BEGIN_SRC sh
       cd ~/Downloads
       wget https://www.phidgets.com/downloads/phidget22/examples/python/Manager/Phidget22_HelloWorld_Python_Ex.zip
       unzip Phidget22_HelloWorld_Python_Ex.zip -d Phidget22_HelloWorld_Python
       python3 ./Phidget22_HelloWorld_Python/HelloWorld.py
     #+END_SRC

** Emacs Tramp Into SBC

   #+BEGIN_SRC
     C-x C-f /ssh:phidget@192.168.0.56:/home/phidget/
   #+END_SRC
